from . import patient
from . import doctor
from . import appointment
from . import departement
from . import room
from . import equipement
from . import operation
from . import facture
from . import hospital_dashboard
